# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="gallois"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/bundler
# BUNDLED_COMMANDS=(rubocop)
# UNBUNDLED_COMMANDS=(foreman spin)

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git osx terminalapp brew copydir copyfile gem rake-fast rails bundler rvm rbenv)

source $ZSH/oh-my-zsh.sh

# User configuration
export PATH=$PATH:/usr/local/go/bin
export PATH="/Applications/LibreOffice.app/Contents/MacOS:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
export PATH=/usr/pgsql-9.5/bin:$PATH
export PATH="./node_modules/.bin:$PATH"

# export MANPATH="/usr/local/man:$MANPATH"
if [[ `uname` != *"Linux"* ]]; then
  export PGDATA=$HOME/pg-data
fi
export DISABLE_SPRING=1

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

export NVIM_TUI_ENABLE_TRUE_COLOR=1

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Go Lang environment variables
export GOPATH=$HOME/work/go
export GOBIN=$GOPATH/bin

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Aliases
alias nvim="NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim"
alias zshconfig="$EDITOR ~/.zshrc"
alias nvimconf="$EDITOR ~/.config/nvim/init.vim"
alias subl="subl -n"
alias nau='nautilus . &'

# Aliases for Tmux
alias tmux='tmux -2'
alias ta='tmux attach -t'
alias tnew='tmux new -s'
alias tls='tmux ls'
alias tkill='tmux kill-session -t'

# Apertium tools
# export PATH="$HOME/Local/bin:$PATH"
# export PKG_CONFIG_PATH="$HOME/Local/lib/pkgconfig:$PKG_CONFIG_PATH"
# export LD_LIBRARY_PATH="$HOME/Local/lib:$LD_LIBRARY_PATH"
# export DYLD_LIBRARY_PATH="$HOME/Local/lib:$DYLD_LIBRARY_PATH"
# export DYLD_FALLBACK_LIBRARY_PATH="$HOME/Local/lib"

# Check rbenv or rvm and init corresponding manager.
if [ -d ~/.rbenv ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
else
  export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
fi

# Loading files like rake, rails from ./bin. It should be after rbenv/rvm initialization.
export PATH="./bin:$PATH"

# Green cursor
echo -ne '\e]12;lightgreen\a'

# Install gems in parallel with bundler.
export BUNDLE_JOBS=4

# Disable cowsay for Ansible
export ANSIBLE_NOCOWS=1
