export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="gallois"
plugins=(bundler rails docker docker-compose git)
source $ZSH/oh-my-zsh.sh

# User configuration
export PATH="$HOME/bin:$PATH"
export PATH="./bin:$PATH"
export PATH="./node_modules/.bin:$PATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# Tmux
alias tmux='tmux -2'
alias ta='tmux attach -t'
alias tnew='tmux new -s'
alias tls='tmux ls'
alias tkill='tmux kill-session -t'

# Fix tmuxinator/tmuxp window titles.
export DISABLE_AUTO_TITLE='true'

# Use vimx if exists (because clipboard support)
if [ -x "$(command -v vimx)" ]; then
  alias vim='vimx'
  export EDITOR='vimx'
else
  export EDITOR='vim'
fi

# Green cursor
echo -ne '\e]12;green\a'

# Ruby and Rails
function rbenv_prompt_info() {
  if [ -e "./.ruby-version" ]; then
    echo "[$(cat .ruby-version)]"
  fi
}

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

export BUNDLE_JOBS=4
export DISABLE_SPRING=1
export SKIP_SIMPLECOV=1

# DevOps tools
export ANSIBLE_NOCOWS=1
export VAGRANT_DEFAULT_PROVIDER=virtualbox

# FZF
source /usr/share/fzf/shell/key-bindings.zsh
export FZF_DEFAULT_COMMAND='rg --files'

# Go
export PATH="$HOME/opt/go/bin:$PATH"
export GOPATH="$HOME/work/go"
export PATH="$GOPATH/bin:$PATH"

# The next line updates PATH for Yandex Cloud CLI.
if [ -f "$HOME/yandex-cloud/path.bash.inc" ]; then source "$HOME/yandex-cloud/path.bash.inc"; fi

# Qt
export PATH="/home/rain/Qt/5.12.6/gcc_64/bin:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
