---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    current_user: '{{ lookup("env", "USER") }}'
    dotfiles_dir: '{{ lookup("env", "PWD") }}/dotfiles'
    ansible_python_interpreter: /opt/homebrew/bin/python3.13
  tasks:
    - name: install homebrew packages
      homebrew:
        name:
          - ag
          - ansible
          - awscli
          - cowsay
          - curl
          - dive
          - fd
          - fnm
          - fortune
          - fzf
          - git
          - go
          - golangci-lint
          - gpg
          - helix
          - htop
          - imagemagick
          - jpegoptim
          - lazygit
          - mise
          - pwgen
          - rg
          - shared-mime-info
          - starship
          - terraform
          - tmux
          - tmuxp
          - vim
          - wget
          - yazi
          - yq
          - zoxide
          - zsh
          # - postgresql@17
          # - redis
        state: present
      tags: brew

    # Git configuration
    - name: set git user name
      git_config:
        name: user.name
        scope: global
        value: '{{ user_name }}'
      tags: git
      
    - name: set git user email
      git_config:
        name: user.email
        scope: global
        value: '{{ user_email }}'
      tags: git
      
    - name: set global gitignore
      git_config:
        name: core.excludesfile
        scope: global
        value: ~/.gitignore_global
      tags: git
      
    - name: link global gitignore
      file: src={{ dotfiles_dir }}/gitignore_global dest=~/.gitignore_global state=link
      tags: git
      
    - name: set push.default simple
      git_config:
        name: push.default
        scope: global
        value: simple
      tags: git

    # Zsh configuration
    - name: clone zgen
      git:
        repo: https://github.com/tarjoilija/zgen.git
        dest: ~/.zgen
        update: yes
      tags: zsh

    - name: symlink zshrc
      file: src={{ dotfiles_dir}}/zshrc dest=~/.zshrc state=link force=yes
      tags: zsh

    # Starship configuration  
    - name: symlink starship config
      file: src={{ dotfiles_dir }}/starship.toml dest=~/.config/starship.toml state=link force=yes
      tags: starship

    # Tmux configuration
    - name: symlink tmux config
      file: src={{ dotfiles_dir}}/tmux.conf dest=~/.tmux.conf state=link
      tags: tmux

    # Vim configuration
    - name: create directory for vim backups and swaps
      file: path=~/.vimtmp state=directory force=yes
      tags: vim
      
    - name: symlink vim config
      file: src={{ dotfiles_dir }}/vim/vimrc.vim dest=~/.vimrc state=link force=yes
      tags: vim
      
    - name: remove old vim directory
      file: path=~/.vim state=absent force=yes
      tags: vim
      
    - name: symlink vim directory
      file: src={{ dotfiles_dir }}/vim dest=~/.vim state=link force=yes
      tags: vim
      
    - name: create dir for minpac
      file: path={{ dotfiles_dir }}/vim/pack/minpac/opt state=directory
      tags: vim
      
    - name: clone minpac
      git:
        repo: git@github.com:k-takata/minpac.git
        dest: '{{ dotfiles_dir }}/vim/pack/minpac/opt/minpac'
        clone: yes
        update: yes
      tags: vim

    # Development tools configuration
    - name: symlink gemrc
      file: src={{ dotfiles_dir}}/gemrc dest=~/.gemrc state=link force=yes
      tags: devtools
      
    - name: create GOPATH directory
      file: path=~/work/go/bin state=directory force=yes
      tags: devtools

    # Helix configuration
    - name: symlink helix config
      file: src={{ dotfiles_dir }}/helix dest=~/.config/helix state=link force=yes
      tags: helix

