- hosts: localhost
  roles:
    - zsh
    - { role: git, tags: git }
    - ruby
    - { role: vim, tags: vim }
    - { role: tmux, tags: tmux }
    # - { role: emacs, tags: emacs }
    - { role: ctags, tags: ctags }
    # - { role: dosbox, tags: dosbox }
