- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/env python3
  roles:
    - zsh
    - { role: git, tags: git }
    - ruby
    - { role: vim, tags: vim }
    - { role: tmux, tags: tmux }
