- hosts: localhost
  vars_prompt:
    - name: user_email
      prompt: 'Enter user email'
      private: false
    - name: user_name
      prompt: 'Enter user name'
      private: false

  roles:
    - zsh
    - emacs
    - git
    - ruby
    - vim
    # - rubygems
    # - ctags
    # - tmux
    # - iterm2
    # - mysql
