- hosts: localhost
  roles:
    - zsh
    - { role: git, tags: git }
    - ruby
    - vim
    - tmux
    - { role: emacs, tags: emacs }
    - { role: ctags, tags: ctags }
    - { role: dosbox, tags: dosbox }
