- name: create directory for backups and swaps
  file: path=~/.vimtmp state=directory
- name: symlink nvim config
  file: src={{ dotfiles_dir }}/nvim dest=~/.config/nvim state=link
- name: symlink vim config
  file: src={{ dotfiles_dir }}/nvim/init.vim dest=~/.vimrc state=link
- name: symlink vim directory
  file: src={{ dotfiles_dir }}/nvim dest=~/.vim state=link
- name: create dir for minpack
  file: path={{ dotfiles_dir }}/nvim/pack/minpac/opt state=directory
- name: clone minpack
  git:
    repo: git@github.com:k-takata/minpac.git
    dest: '{{ dotfiles_dir }}/nvim/pack/minpac/opt/minpac'
    clone: yes
    update: yes
