- name: ensure .config
  file: path=~/.config state=directory

- name: symlink nvim directory
  file: src={{ dotfiles_dir }}/nvim dest=~/.config/nvim state=link force=yes

- name: ensure .local/share/nvim
  file: path=~/.local/share/nvim state=directory

- name: clone lazy.vim
  git:
    repo: git@github.com:folke/lazy.nvim.git
    dest: ~/.local/share/nvim/lazy/lazy.nvim
    clone: yes
    update: yes
